#############################################################
# AEYE AI OpticNet DockerFile
# Created By Yoonchul Chung
# Created At 2024.08.03
# Welcome to Visit Github : https://github.com/Yoonchulchung
#############################################################
FROM tensorflow/tensorflow:1.12.0-rc1-gpu-py3


#############################################################
# Install Dependencies

RUN pip install keras==2.2.4
RUN pip install pycm==1.9 matplotlib sklearn

RUN pip install --upgrade pip
RUN pip install opencv-python
RUN pip install Flask==1.1.4
RUN pip install colorama

RUN apt-get update && apt-get install -y libgl1-mesa-glx

#############################################################
# Copy Files
WORKDIR /app/
COPY /AI/ /app/

#############################################################
# Cleaning

#############################################################
# RUN

EXPOSE 3000
EXPOSE 8888
EXPOSE 6006
# CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=5000", "--no-browser", "--allow-root"]

CMD ["python", "run.py", "--p", "3000"]

