version: '3.8'

services:
  backend:
    image: aeye_ai_back:1.0
    container_name: ai_back_container
    build:
      context: ..
      dockerfile: Docker/BackEnd/Dockerfile
    ports:
    - "6000:6000"
    volumes:
    - /AEYE_AI_Back_3_2/:/app/
    networks:
      - ai_network
    command: python manage.py runserver 0.0.0.0:6000
    
  ai:
    image: aeye_ai:1.0
    container_name: opticnet_container
    build:
      context: ..
      dockerfile: Docker/AI/Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - /AI/:/app/
    networks:
      - ai_network
    command: python run.py

networks:
  ai_network:
    driver: bridge