#############################################################
# AEYE AI Docker Compose File
# Created By Yoonchul Chung
# Created At 2024.08.03
# Welcome to Visit Github : https://github.com/Yoonchulchung
#############################################################

version: '3.8'

services:
  backend:
    image: aeye_ai_back:1.0
    container_name: ai_back_container
    build:
      context: ..
      dockerfile: Docker/BackEnd/Dockerfile
    ports:
    - "8000:8000"
    volumes:  
    - ../AEYE_AI_Back_3_2/:/app/
    networks:
      - ai_network
    command: python manage.py runserver 0.0.0.0:8000
    
  ai:
    image: aeye_ai:1.0
    container_name: opticnet_container
    build:
      context: ..
      dockerfile: Docker/AI/Dockerfile
    ports:
    - "3000:3000"
    - "6006:6006"
    - "8888:8888"
    runtime: nvidia # If NVIDIA Container Toolkit is not installed, turn off the code.
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # If NVIDIA Container Toolkit is not installed, turn off the code.
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility # If NVIDIA Container Toolkit is not installed, turn off the code.
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
    - ../AI/:/app/
    networks:
      - ai_network
    command: python run.py

networks:
  ai_network:
    driver: bridge