version: '3.8'

services:
  backend:
    image: aeye_ai_back:1.0
    container_name: ai_back_container
    build:
      context: ..
      dockerfile: Docker/BackEnd/Dockerfile
    ports:
    - "2000:2000"
    volumes:
    - ../AEYE_AI_Back_3_2/:/app/
    networks:
      - ai_network
    command: python3.5 manage.py runserver 0.0.0.0:2000
    
  ai:
    image: aeye_ai:1.0
    container_name: opticnet_container
    build:
      context: ..
      dockerfile: Docker/AI/Dockerfile
    ports:
    - "7070:7070"
    - "6006:6006"
    - "8888:8888"
    volumes:
    - ../AI/:/app/
    networks:
      - ai_network
    command: python run.py --p 7070

networks:
  ai_network:
    driver: bridge