# Generated by Django 3.2 on 2024-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiate_AI_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='UploadedImage',
            new_name='Request_Image_Model',
        ),
    ]
